### ISSUE TITLE
CLI unable to delele empty folder, and instead of this it deletes all folders

### ISSUE THREAD

**Issue by lksgithub** [jfrog/jfrog-cli-go#206]
I ran the following command to delete empty folder under a repo:
jfrog rt delete --spec=housekeep_empty_folder.json --quiet=true --dry-run=true

, where housekeep_empty_folder.json has the following content
```
{
  "files": [
   {
     "aql": {
       "items.find": {
         "repo": "deployment-upload-repo",
         "type": "folder",
         "size": 0
       }
     }
   }
  ]
}
```

Expected results:
One folder is deleted becuase there is only one empty folder under the given repo

Actual result:
All folders are deleted

**Comment by DimaNevelev** [comment]
@lksgithub,
The CLI deletes items returned by the AQL so the root cause is the provided AQL.
From AQL perspective, the "size" field is related to the size of the item. In case of a folder, it will always be 0.
Please see [this knowledge-base page](https://jfrog.com/knowledge-base/empty-folder-clean-up/). It describes the standard way of cleaning empty folders in Artifactory.

**Comment by eyalbe4** [comment]
@lksgithub,
It is probably best to keep this space for questions and issues related to JFrog CLI.
