### ISSUE TITLE
Add the ability to upload broken symlinks.

### ISSUE THREAD

**Issue by yudkeh** [jfrog/jfrog-cli-go#229]
Sometimes there are symlink which are broken in the machine which used for upload but when they will get downloaded by the users they will work as they include path to an existing folder, therefore there is a need to add the ability to upload broken symlink.

**Comment by trinhta** [comment]
Currently the broken symlinks are totally ignored during the upload, but the ideal solution for broken symlinks is that Artifactory should create a "marker" in Artifactory for the bad symlinks during the upload so that later when the user downloads from Artifactory, using the --symlink option, the same (bad) symlinks will appear in his workspace.

**Comment by RobiNino** [comment]
Hi @trinhta @yudkeh, 
We are currently working on a solution to this issue, and will release it as soon as possible.

**Comment by RobiNino** [comment]
Hi @trinhta,
CLI version 1.21.0 is now released and includes a fix for this issue.
We would love to hear your feedback regarding this matter.
@yudkeh
