### ISSUE TITLE
Current tip revision issue?

### ISSUE THREAD

**Issue by dsoprea** [jfrog/jfrog-cli-go#315]
```
~/development/gopath/src$ rm -fr github.com/jfrog

~/development/gopath/src$ go get -t github.com/jfrog/jfrog-cli-go
# cd .; git clone https://github.com/jfrog/jfrog-cli-go /home/local/MAGICLEAP/doprea/development/gopath/src/github.com/jfrog/jfrog-cli-go
Cloning into '/home/local/MAGICLEAP/doprea/development/gopath/src/github.com/jfrog/jfrog-cli-go'...
Triggering /home/local/MAGICLEAP/doprea/development/gopath/src/github.com/jfrog/jfrog-cli-go/.git/hooks/post-checkout
fetch: Fetching reference refs/heads/master
[4bf4c8c0fef3f5c8cf6f255d1c784377138588c0a9abe57e440bce3ccb350c2e] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/jfrog/jfrog-cli-go.git/info/lfs'
package github.com/jfrog/jfrog-cli-go: exit status 2
```

**Comment by RobiNino** [comment]
Hi @dsoprea ,
If building the JFrog CLI is what you are after, kindly follow the instructions under the '[Building the Executable](https://github.com/jfrog/jfrog-cli-go/blob/master/README.md#building-the-executable)' section in the README.

Otherwise, please provide additional information about what you were trying to do, and what is the problem you encounter.

Thanks!

**Comment by dsoprea** [comment]
See above. What I was "trying to do" was a go-get.

Here's a simple git-clone:

```
$ git clone https://github.com/jfrog/jfrog-cli-go/
Cloning into 'jfrog-cli-go'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 12043 (delta 22), reused 34 (delta 15), pack-reused 11981
Receiving objects: 100% (12043/12043), 31.51 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (5914/5914), done.
Triggering /home/local/MAGICLEAP/doprea/development/go/jfrog-cli-go/.git/hooks/post-checkout
fetch: Fetching reference refs/heads/master
[4bf4c8c0fef3f5c8cf6f255d1c784377138588c0a9abe57e440bce3ccb350c2e] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/jfrog/jfrog-cli-go.git/info/lfs'
```

Let's see if we can keep this issue open for at least a third month before I can get a serious response.

**Comment by RobiNino** [comment]
I apologize for the late response on the previous comment.
According to the log you provided, it seems that the ‘git clone’ runs successfully, but a git LFS hook fails.
You previously reported #63 that also seems like a ‘git lfs’ error. Did you manage to solve it last time?

The jfrog-cli-go project does not track any lfs files, and since the default git LFS post-checkout hook does not usually perform a ‘git lfs fetch’ no error should be encountered.
I couldn't reproduce the problem on a clean git configuration, and neither after installing git-lfs and running 'git clone ...'.

If you have a manual hook configured, can you please share it with us? Can you run ‘git clone’ with GIT_TRACE=1?
Otherwise, can you try cloning without git hooks enabled?

BTW, the reason we are instructing to build with 'git clone' and not 'go get' is because 'go get github.com/jfrog/jfrog-cli-go' currently fails due to the location of the main.go. A simple call of 'go get' requires main.go to be in the repository's main folder, but in the jfrog-cli-go this isn't currently the case due to past requirements. We are looking into fixing this in the future.

Thanks

**Comment by dsoprea** [comment]
Ok.

Well, it looks like having "templatedir = ~/.git-templates" in my config is producing anomalous behavior. Weird. Thanks for clarifying things.
