### ISSUE TITLE
Documentation for Xray missing?

### ISSUE THREAD

**Issue by an-sush** [jfrog/jfrog-cli-go#327]
This [page](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI) talks about xr target which is for Xray but there is no link to Xray Cli page. Where do I get help?

**Comment by eyalbe4** [comment]
@an-sush,
Currently JFrog CLI supports only one Xray related command - offline-update.
There's currently no online documentation for this command, because its syntax is generated automatically by the Xray UI. You can read more about the offline update process [here](https://www.jfrog.com/confluence/display/XRAY/Configuring+Xray#ConfiguringXray-OfflineSynchronization).
Please let us know if you have additional questions about this.
